# Generated by Django 3.1.7 on 2021-03-08 07:30

from django.db import migrations, models
import django.db.models.deletion
import sportnew.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='image-category/')),
                ('background', models.ImageField(upload_to='category/background/{title}')),
            ],
        ),
        migrations.CreateModel(
            name='SportNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('writer', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='sportnew.Category')),
                ('default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_category', to='sportnew.category')),
            ],
        ),
        migrations.CreateModel(
            name='SportNewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sportnew.models.image_upload_to)),
                ('sportnew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportnew.sportnew')),
            ],
        ),
    ]
